# Generated by Django 4.2.30 on 2026-05-08 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('exited', 'Exited')], default='active', max_length=16)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('exited_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SiteDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='planned', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('shift_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('billing_type', models.CharField(choices=[('billable', 'Billable'), ('non_billable', 'Non-Billable')], default='billable', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deployments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='deployment.employee')),
            ],
            options={
                'verbose_name': 'Site Deployment',
                'verbose_name_plural': 'Site Deployments',
                'ordering': ['-start_date'],
            },
        ),
    ]
