# Generated by Django 4.2.30 on 2026-05-08 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_client_scope_node_and_more'),
        ('hiring', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0001_initial'),
        ('deployment', '0001_initial'),
        ('jobs', '0001_initial'),
        ('mrf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedeployment',
            name='hiring_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='hiring.hiringapplication'),
        ),
        migrations.AddField(
            model_name='sitedeployment',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='jobs.jobrole'),
        ),
        migrations.AddField(
            model_name='sitedeployment',
            name='mrf_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='mrf.mrflineitem'),
        ),
        migrations.AddField(
            model_name='sitedeployment',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_deployments', to='core.organization'),
        ),
        migrations.AddField(
            model_name='sitedeployment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='sites.siteprofile'),
        ),
        migrations.AddField(
            model_name='employee',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_records', to='talent.candidate'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='jobs.jobrole'),
        ),
        migrations.AddField(
            model_name='employee',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sitedeployment',
            index=models.Index(fields=['org', 'status'], name='deployment__org_id_8e6d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='sitedeployment',
            index=models.Index(fields=['site', 'status'], name='deployment__site_id_956825_idx'),
        ),
        migrations.AddIndex(
            model_name='sitedeployment',
            index=models.Index(fields=['employee', 'status'], name='deployment__employe_a0cf2b_idx'),
        ),
        migrations.AddIndex(
            model_name='sitedeployment',
            index=models.Index(fields=['job_role', 'status'], name='deployment__job_rol_d1f212_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['org', 'status'], name='deployment__org_id_c5f259_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['job_role', 'status'], name='deployment__job_rol_70d1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user'], name='deployment__user_id_8fa3c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('org', 'employee_code'), name='unique_employee_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_normalized', ''), _negated=True), fields=('org', 'phone_normalized'), name='unique_employee_phone_per_org'),
        ),
    ]
