# Generated by Django 4.2.29 on 2026-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(check=models.Q(('employee_code', ''), _negated=True), name='employee_code_not_blank'),
        ),
    ]
