# Generated by Django 4.2.30 on 2026-08-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0004_deployment_history_and_active_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='field_is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='field_login_failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='field_pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='employee',
            name='field_provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='field_provisioning_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('provisioned', 'Provisioned'), ('failed', 'Failed'), ('deprovisioned', 'Deprovisioned')], max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='FieldProvisioningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('action', models.CharField(choices=[('provision', 'Provision'), ('deprovision', 'Deprovision'), ('update', 'Update')], max_length=16)),
                ('payload_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_logs', to='deployment.employee')),
            ],
            options={
                'verbose_name': 'Field Provisioning Log',
                'verbose_name_plural': 'Field Provisioning Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
