# Generated by Django 4.2.30 on 2026-05-29 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('workflow_task_assigned', 'Workflow Task Assigned'), ('workflow_completed', 'Workflow Completed'), ('sales_survey_assigned', 'Sales Survey Assigned'), ('sales_survey_completed', 'Sales Survey Completed'), ('mobilisation_operations_assigned', 'Mobilisation Operations Assigned'), ('mobilisation_setup_completed', 'Mobilisation Setup Completed'), ('system', 'System')], default='system', max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['org', '-created_at'], name='notificatio_org_id_776ad3_idx'), models.Index(fields=['target_type', 'target_id'], name='notificatio_target__08ac26_idx')],
            },
        ),
    ]
