# Generated by Django 4.2.30 on 2026-07-08 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0006_source_audit_fields'),
        ('core', '0002_add_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGeofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.PositiveIntegerField(default=100, help_text='Allowed radius in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('require_within_geofence', models.BooleanField(default=True, help_text='Reject check-in if outside geofence')),
                ('allowed_wifi_ssids', models.JSONField(blank=True, default=list, help_text='List of allowed WiFi SSIDs for additional verification')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geofence', to='sites.siteprofile')),
            ],
            options={
                'verbose_name': 'Site Geofence',
                'verbose_name_plural': 'Site Geofences',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_at', models.DateTimeField()),
                ('check_in_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('check_in_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('check_in_address', models.TextField(blank=True)),
                ('check_in_accuracy_m', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=6, null=True)),
                ('check_in_photo', models.ImageField(blank=True, help_text='Optional selfie/photo at check-in', null=True, upload_to='attendance/checkin/%Y/%m/%d/')),
                ('check_in_device_info', models.JSONField(blank=True, default=dict)),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_address', models.TextField(blank=True)),
                ('check_out_accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('check_out_photo', models.ImageField(blank=True, null=True, upload_to='attendance/checkout/%Y/%m/%d/')),
                ('check_out_device_info', models.JSONField(blank=True, default=dict)),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active (Checked In)'), ('completed', 'Completed (Checked Out)'), ('missed_checkout', 'Missed Check-out (Auto-closed)'), ('manual_adjustment', 'Manually Adjusted')], default='active', max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('break_minutes', models.PositiveIntegerField(default=0)),
                ('expected_shift_start', models.TimeField(blank=True, null=True)),
                ('expected_shift_end', models.TimeField(blank=True, null=True)),
                ('shift_date', models.DateField(help_text='Date of the shift (for night shifts crossing midnight)')),
                ('auto_closed', models.BooleanField(default=False)),
                ('auto_closed_at', models.DateTimeField(blank=True, null=True)),
                ('manual_override_reason', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='sites.client')),
                ('employee', models.ForeignKey(limit_choices_to={'user_type': 'internal'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
                ('manual_override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_manual_overrides', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, help_text='Site where attendance was marked (from employee assignment or GPS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='sites.siteprofile')),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-check_in_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('org', 'Organization'), ('client', 'Client'), ('site', 'Site')], default='org', max_length=16)),
                ('standard_shift_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('max_shift_hours', models.DecimalField(decimal_places=1, default=12.0, max_digits=4)),
                ('min_break_minutes', models.PositiveIntegerField(default=30, help_text='Min break after 6 hours')),
                ('check_in_grace_minutes', models.PositiveIntegerField(default=15)),
                ('check_out_grace_minutes', models.PositiveIntegerField(default=15)),
                ('auto_close_after_hours', models.PositiveIntegerField(default=14, help_text='Auto close session after hours')),
                ('auto_close_enabled', models.BooleanField(default=True)),
                ('overtime_after_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('max_overtime_hours_per_day', models.DecimalField(decimal_places=1, default=4.0, max_digits=4)),
                ('late_threshold_minutes', models.PositiveIntegerField(default=15)),
                ('early_departure_threshold_minutes', models.PositiveIntegerField(default=15)),
                ('require_photo', models.BooleanField(default=False)),
                ('require_within_geofence', models.BooleanField(default=True)),
                ('max_gps_accuracy_meters', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='sites.client')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='core.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='sites.siteprofile')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correction_type', models.CharField(choices=[('check_in_time', 'Check-in Time'), ('check_out_time', 'Check-out Time'), ('add_session', 'Add Missing Session'), ('remove_session', 'Remove Invalid Session'), ('shift_change', 'Shift Assignment Change'), ('break_adjustment', 'Break Time Adjustment')], max_length=20)),
                ('reason', models.TextField()),
                ('original_data', models.JSONField(blank=True, default=dict)),
                ('corrected_data', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('review_notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('break_type', models.CharField(choices=[('lunch', 'Lunch'), ('tea', 'Tea/Coffee'), ('personal', 'Personal'), ('other', 'Other')], default='lunch', max_length=16)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_auto', models.BooleanField(default=False, help_text='Auto-detected break (e.g., geofence exit)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['session', 'start_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['employee', 'check_in_at'], name='attendance__employe_6fd1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['site', 'check_in_at'], name='attendance__site_id_66aaa2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status', 'check_in_at'], name='attendance__status_5c624a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['shift_date', 'employee'], name='attendance__shift_d_09f074_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('employee', 'shift_date'), name='unique_active_session_per_employee_per_day'),
        ),
        migrations.AddConstraint(
            model_name='attendancepolicy',
            constraint=models.UniqueConstraint(fields=('org', 'scope', 'client', 'site', 'effective_from'), name='unique_attendance_policy_per_scope_date'),
        ),
    ]
