# Generated by Django 4.2.30 on 2026-07-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycategory',
            name='category_type',
            field=models.CharField(choices=[('ppe', 'PPE'), ('it_asset', 'IT Asset'), ('machinery', 'Machinery'), ('tools', 'Tools'), ('office_asset', 'Office Asset'), ('electrical', 'Electrical Materials'), ('plumbing', 'Plumbing Materials'), ('construction', 'Construction Materials'), ('furniture', 'Furniture'), ('uniform', 'Uniform'), ('vehicle', 'Vehicle'), ('stationery', 'Stationery'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='amc_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='amc_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='amc_vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='assigned_department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='assigned_project',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='assigned_site',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='assigned_to_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category_type',
            field=models.CharField(blank=True, choices=[('ppe', 'PPE'), ('it_asset', 'IT Asset'), ('machinery', 'Machinery'), ('tools', 'Tools'), ('office_asset', 'Office Asset'), ('electrical', 'Electrical Materials'), ('plumbing', 'Plumbing Materials'), ('construction', 'Construction Materials'), ('furniture', 'Furniture'), ('uniform', 'Uniform'), ('vehicle', 'Vehicle'), ('stationery', 'Stationery'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Under Maintenance'), ('disposed', 'Disposed'), ('lost', 'Lost'), ('archived', 'Archived'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='maintenance_cycle_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='max_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='qr_code',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='rack_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='return_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sub_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warranty_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InventoryItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('purchased', 'Purchased'), ('assigned', 'Assigned'), ('transferred', 'Transferred'), ('returned', 'Returned'), ('maintenance', 'Sent for Maintenance'), ('lost', 'Reported Lost'), ('disposed', 'Disposed'), ('archived', 'Archived'), ('updated', 'Updated')], max_length=50)),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
