# Generated by Django 4.2.30 on 2026-07-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_department'),
        ('inventory', '0002_inventorycategory_category_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('low_stock_alert_threshold_percent', models.IntegerField(default=10)),
                ('warranty_alert_days_before', models.IntegerField(default=30)),
                ('admin_emails_for_alerts', models.CharField(blank=True, help_text='Comma-separated emails', max_length=500)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_settings', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryBillingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_type', models.CharField(blank=True, choices=[('ppe', 'PPE'), ('it_asset', 'IT Asset'), ('machinery', 'Machinery'), ('tools', 'Tools'), ('office_asset', 'Office Asset'), ('electrical', 'Electrical Materials'), ('plumbing', 'Plumbing Materials'), ('construction', 'Construction Materials'), ('furniture', 'Furniture'), ('uniform', 'Uniform'), ('vehicle', 'Vehicle'), ('stationery', 'Stationery'), ('other', 'Other')], max_length=50)),
                ('is_billable', models.BooleanField(default=False)),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_billing_rules', to='core.organization')),
            ],
            options={
                'unique_together': {('org', 'category_type')},
            },
        ),
    ]
