# Generated by Django 4.2.30 on 2026-07-08 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0006_source_audit_fields'),
        ('inventory', '0004_uniformkit_inventoryitem_uniform_kit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('transfer', 'Transfer'), ('issue', 'Issue'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('damage', 'Damage'), ('disposal', 'Disposal'), ('audit', 'Audit'), ('consumption', 'Consumption'), ('purchase', 'Purchase'), ('vendor_return', 'Vendor Return'), ('site_return', 'Site Return'), ('branch_return', 'Branch Return')], max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('reference_module', models.CharField(blank=True, max_length=100)),
                ('previous_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_branch', to='core.scopenode')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_client', to='sites.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_project', to='core.scopenode')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_site', to='sites.siteprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
