# Generated by Django 4.2.30 on 2026-07-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysettings',
            name='storage_locations',
            field=models.JSONField(blank=True, default=list, help_text='Configurable list of storage locations'),
        ),
    ]
