# Generated by Django 4.2.30 on 2026-07-09 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_department'),
        ('inventory', '0006_inventorysettings_storage_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='core.scopenode'),
        ),
    ]
