# Generated by Django 4.2.30 on 2026-07-09 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_department'),
        ('workflow', '0011_alter_approvalroute_trigger_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_alter_inventoryitem_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('form_schema', models.JSONField(blank=True, default=list, help_text='Array of field objects defining the dynamic form (e.g. label, type, required)')),
                ('is_billable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_request_types', to='core.organization')),
                ('workflow_template', models.ForeignKey(blank=True, help_text='The dynamic approval chain for this request type.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowtemplate')),
            ],
            options={
                'unique_together': {('org', 'code')},
            },
        ),
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_data', models.JSONField(blank=True, default=dict, help_text='User input matching the request type schema')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved / Waiting Assignment'), ('assigned', 'Assigned / Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='inventory.inventoryitem')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requests', to='core.organization')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='inventory.inventoryrequesttype')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requests', to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_request_instance', to='workflow.workflowinstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_required', models.BooleanField(default=True)),
                ('warranty_tracking', models.BooleanField(default=False)),
                ('return_required', models.BooleanField(default=False)),
                ('replacement_allowed', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='inventory.inventorycategory')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_policies', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_assign_to_employee', models.BooleanField(default=True)),
                ('can_assign_to_site', models.BooleanField(default=True)),
                ('can_assign_to_client', models.BooleanField(default=False)),
                ('can_assign_to_department', models.BooleanField(default=False)),
                ('can_assign_to_project', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='inventory.inventorycategory')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
