# Generated by Django 4.2.29 on 2026-05-14 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intake', '0003_rename_intake_intak_mobile__idx_intake_inta_mobile__2007f7_idx_and_more'),
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('normalized_degree', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('institute', models.CharField(blank=True, max_length=255)),
                ('start_year', models.SmallIntegerField(blank=True, null=True)),
                ('end_year', models.SmallIntegerField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Education',
                'verbose_name_plural': 'Candidate Educations',
                'ordering': ['-end_year'],
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('normalized_title', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Experience',
                'verbose_name_plural': 'Candidate Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_json', models.JSONField(blank=True, default=dict)),
                ('normalized_json', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('career_level', models.CharField(blank=True, max_length=64)),
                ('primary_domain', models.CharField(blank=True, max_length=128)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parsed Resume',
                'verbose_name_plural': 'Parsed Resumes',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='availability_status',
            field=models.CharField(choices=[('available_now', 'Available Now'), ('available_from_date', 'Available From Date'), ('currently_deployed', 'Currently Deployed'), ('notice_period', 'Notice Period'), ('not_available', 'Not Available'), ('unknown', 'Unknown')], default='unknown', max_length=24),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='do_not_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='talent.candidate'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted'), ('duplicate', 'Duplicate'), ('employee_converted', 'Employee Converted'), ('do_not_contact', 'Do Not Contact')], default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notice_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateskill',
            name='proficiency',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20),
        ),
        migrations.AddField(
            model_name='candidateskill',
            name='source',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='candidateskill',
            name='source_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='talent.resume'),
        ),
        migrations.AddField(
            model_name='candidateskill',
            name='years_experience',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='cleaned_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='extraction_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='extraction_engine',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resume',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resume',
            name='manual_review_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ocr_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='parser_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='parser_engine',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resume',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='source_intake_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='intake.intakedocument'),
        ),
        migrations.AddField(
            model_name='resume',
            name='source_type',
            field=models.CharField(choices=[('qr_intake', 'QR Intake'), ('manual_upload', 'Manual Upload'), ('recruiter_upload', 'Recruiter Upload'), ('portal', 'Portal'), ('referral', 'Referral'), ('import_', 'Import')], default='manual_upload', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('ocr_required', 'OCR Required'), ('parsing', 'Parsing'), ('validating', 'Validating'), ('indexed', 'Indexed'), ('manual_review', 'Manual Review'), ('failed', 'Failed'), ('duplicate_file', 'Duplicate File')], default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['org', 'lifecycle_status'], name='talent_cand_org_id_cd5c27_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['org', 'availability_status'], name='talent_cand_org_id_ba0390_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='talent_cand_email_dace23_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['phone_normalized'], name='talent_cand_phone_n_e03f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['file_hash'], name='talent_resu_file_ha_642761_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['candidate', 'status'], name='talent_resu_candida_030b19_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['source_intake_document'], name='talent_resu_source__b29d77_idx'),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_resume', to='talent.resume'),
        ),
        migrations.AddField(
            model_name='candidateexperience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='talent.candidate'),
        ),
        migrations.AddField(
            model_name='candidateexperience',
            name='source_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='talent.resume'),
        ),
        migrations.AddField(
            model_name='candidateeducation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='talent.candidate'),
        ),
        migrations.AddField(
            model_name='candidateeducation',
            name='source_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='talent.resume'),
        ),
    ]
