# Generated by Django 4.2.29 on 2026-05-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_talent_hiring_a'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('source_intake_document__isnull', False)), fields=('source_intake_document',), name='unique_resume_per_intake_document'),
        ),
    ]
