# Generated by Django 4.2.30 on 2026-06-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0007_document_type_and_excel_import_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='collar_type',
            field=models.CharField(blank=True, choices=[('white_collar', 'White Collar'), ('blue_collar', 'Blue Collar')], max_length=20),
        ),
    ]
