# Generated by Django 4.2.30 on 2026-06-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0008_candidate_collar_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('qr', 'QR Code'), ('portal', 'Portal'), ('manual', 'Manual'), ('referral', 'Reference'), ('import_', 'Import'), ('linkedin', 'LinkedIn'), ('naukri', 'Naukri'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='manual', max_length=16),
        ),
    ]
