# Generated by Django 4.2.30 on 2026-07-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0010_candidate_billing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeimportbatch',
            name='billing_type',
            field=models.CharField(blank=True, choices=[('billable', 'Billable'), ('non_billable', 'Non-billable')], max_length=20, null=True),
        ),
    ]
