# Generated by Django 4.2.30 on 2026-08-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0011_resumeimportbatch_billing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
