# Generated by Django 4.2.30 on 2026-08-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0012_candidate_alternate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC'), ('txt', 'Text'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('png', 'PNG'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='resumeimportbatch',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC'), ('txt', 'Text'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('png', 'PNG'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.AlterField(
            model_name='resumeimportitem',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC'), ('txt', 'Text'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('png', 'PNG'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
    ]
