# Generated by Django 4.2.29 on 2026-05-08 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('wages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by_type', models.CharField(choices=[('internal', 'Internal'), ('client', 'Client')], default='internal', max_length=16)),
                ('mrf_type', models.CharField(choices=[('new_hiring', 'New Hiring'), ('replacement', 'Replacement'), ('headcount_increase', 'Headcount Increase'), ('rate_revision', 'Rate Revision')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('hr_review', 'HR Review'), ('finance_review', 'Finance Review'), ('admin_review', 'Admin/HOD Review'), ('client_review', 'Client Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('billing_type', models.CharField(choices=[('billable', 'Billable'), ('non_billable', 'Non-Billable')], max_length=16)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('client_visible', models.BooleanField(default=False, help_text='Whether this MRF is visible to the client user portal.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requests', to='core.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manpower_requests', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower_requests', to='sites.siteprofile')),
            ],
            options={
                'verbose_name': 'Manpower Request',
                'verbose_name_plural': 'Manpower Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MRFLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headcount', models.PositiveIntegerField()),
                ('replacement_for_employee', models.CharField(blank=True, max_length=255)),
                ('required_skills', models.JSONField(default=list)),
                ('min_wage_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wage_min_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wage_max_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrf_line_items', to='jobs.jobrole')),
                ('mrf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='mrf.manpowerrequest')),
                ('site_role_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrf_line_items', to='sites.siterolerequirement')),
                ('wage_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrf_line_items', to='wages.wagecategory')),
            ],
            options={
                'verbose_name': 'MRF Line Item',
                'verbose_name_plural': 'MRF Line Items',
            },
        ),
        migrations.AddIndex(
            model_name='manpowerrequest',
            index=models.Index(fields=['org', 'status'], name='mrf_manpowe_org_id_89f91a_idx'),
        ),
        migrations.AddIndex(
            model_name='manpowerrequest',
            index=models.Index(fields=['site', 'status'], name='mrf_manpowe_site_id_4f0b75_idx'),
        ),
    ]
