# Generated by Django 4.2.29 on 2026-05-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_department'),
        ('mrf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerrequest',
            name='requesting_department',
            field=models.ForeignKey(blank=True, help_text='Department/team raising the manpower request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_mrfs', to='core.department'),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='required_department',
            field=models.ForeignKey(blank=True, help_text='Department/service where manpower is needed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_mrfs', to='core.department'),
        ),
    ]
