# Generated by Django 4.2.29 on 2026-05-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('mrf', '0002_manpowerrequest_requesting_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerrequest',
            name='budget_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrf_requests', to='budgets.budgetplan'),
        ),
        migrations.AddField(
            model_name='mrflineitem',
            name='budget_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrf_line_items', to='budgets.budgetplan'),
        ),
    ]
