# Generated by Django 4.2.29 on 2026-05-15 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0003_add_budget_plan_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRFSupportRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laptop_required', models.BooleanField(default=False)),
                ('desktop_required', models.BooleanField(default=False)),
                ('mail_id_required', models.BooleanField(default=False)),
                ('hrms_login_required', models.BooleanField(default=False)),
                ('outlook_required', models.BooleanField(default=False)),
                ('ms_office_required', models.BooleanField(default=False)),
                ('windows_required', models.BooleanField(default=False)),
                ('own_or_rental', models.CharField(blank=True, max_length=64)),
                ('sim_card_required', models.BooleanField(default=False)),
                ('data_card_required', models.BooleanField(default=False)),
                ('uniform_required', models.BooleanField(default=False)),
                ('visiting_cards_required', models.BooleanField(default=False)),
                ('seating_required', models.BooleanField(default=False)),
                ('admin_location', models.CharField(blank=True, max_length=255)),
                ('admin_other', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'MRF Support Requirement',
                'verbose_name_plural': 'MRF Support Requirements',
            },
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='ctc_budget_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='education_requirement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='experience_max_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='experience_min_years',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='gender_preference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='mis_requirement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='other_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='reference_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='reporting_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='request_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='salary_range_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='special_requirement',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='manpowerrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('request_number', ''), _negated=True), fields=('org', 'request_number'), name='unique_mrf_request_number_per_org_when_set'),
        ),
        migrations.AddField(
            model_name='mrfsupportrequirement',
            name='mrf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_requirement', to='mrf.manpowerrequest'),
        ),
    ]
