# Generated by Django 4.2.30 on 2026-06-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0005_mrf_commercial_override_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrflineitem',
            name='internal_budget_variance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mrflineitem',
            name='internal_budget_variance_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mrflineitem',
            name='internal_previous_employee_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mrflineitem',
            name='internal_requested_monthly_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
