# Generated by Django 4.2.30 on 2026-07-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0006_mrflineitem_internal_budget_variance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerrequest',
            name='has_special_client_req',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='is_budget_deviation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manpowerrequest',
            name='preferred_flow_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard (Includes Finance & Admin)'), ('fast_track', 'Fast Track (Bypasses Finance & Admin)')], max_length=32, null=True),
        ),
    ]
