# Generated by Django 4.2.30 on 2026-05-28 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobilisation', '0002_mobilisation_type_scope_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilisationsetuprequest',
            name='assigned_operations_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mobilisation_setup_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilisationsetuprequest',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilisationsetuprequest',
            name='setup_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_mobilisation_setup_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilisationsetuprequest',
            name='submitted_to_operations_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilisationsetuprequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('operations_setup', 'Operations Setup'), ('setup_completed', 'Setup Completed'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=16),
        ),
    ]
