# Generated by Django 4.2.30 on 2026-05-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_source_audit_fields'),
        ('jobs', '0001_initial'),
        ('mobilisation', '0003_mobilisationsetuprequest_assigned_operations_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilisationproposeddepartment',
            options={'ordering': ['sort_order', 'name', 'id'], 'verbose_name': 'Mobilisation Proposed Department', 'verbose_name_plural': 'Mobilisation Proposed Departments'},
        ),
        migrations.AddField(
            model_name='mobilisationproposeddepartment',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked system-required rows, such as Client Administration, cannot be removed.'),
        ),
        migrations.AddField(
            model_name='mobilisationproposeddepartment',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobilisationproposeddepartment',
            name='source_key',
            field=models.CharField(blank=True, help_text='Stable builder/suggestion key used for idempotent setup generation.', max_length=128),
        ),
        migrations.AddField(
            model_name='mobilisationsetuprequest',
            name='setup_strategy',
            field=models.CharField(choices=[('simple', 'Simple'), ('role_grouped', 'Role Grouped'), ('custom', 'Custom')], default='custom', help_text='How the operations setup builder was last generated/saved.', max_length=20),
        ),
        migrations.CreateModel(
            name='MobilisationProposedDepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_headcount_snapshot', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilisation_department_role_mappings', to='jobs.jobrole')),
                ('proposed_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='mobilisation.mobilisationproposeddepartment')),
                ('real_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilisation_department_role_mappings', to='sites.siteprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_department_roles', to='mobilisation.mobilisationsetuprequest')),
                ('site_role_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobilisation_department_mappings', to='sites.siterolerequirement')),
            ],
            options={
                'verbose_name': 'Mobilisation Proposed Department Role',
                'verbose_name_plural': 'Mobilisation Proposed Department Roles',
                'db_table': 'mobilisation_proposed_department_role',
                'ordering': ['real_site__name', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['request', 'is_active'], name='mobilisatio_request_0a6bb3_idx'), models.Index(fields=['proposed_department', 'is_active'], name='mobilisatio_propose_5c9707_idx'), models.Index(fields=['site_role_requirement', 'is_active'], name='mobilisatio_site_ro_4d10c8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mobilisationproposeddepartmentrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('request', 'site_role_requirement'), name='unique_active_mob_role_assignment'),
        ),
    ]
