# Generated by Django 4.2.30 on 2026-07-02 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('session_status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('timed_out', 'Timed Out')], default='active', max_length=32)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('under_hours', 'Under Hours'), ('absent', 'Absent')], default='present', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', 'login_time'], name='audit_usera_user_id_05bbed_idx'), models.Index(fields=['login_time'], name='audit_usera_login_t_64735b_idx')],
            },
        ),
    ]
