# Generated by Django 4.2.30 on 2026-07-02 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0002_useractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Daily Attendance & Session Logs Report', max_length=255)),
                ('body', models.TextField(default='Hello Admin,\n\nPlease find attached the daily user attendance and session activity report.\n\nRegards,\nLogicon Team')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Report Settings',
                'verbose_name_plural': 'Email Report Settings',
            },
        ),
    ]
