# Generated by Django 4.2.29 on 2026-05-08 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0001_initial'),
        ('wages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('contact_name', models.CharField(blank=True, max_length=128)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('industry', models.CharField(blank=True, max_length=128)),
                ('billing_address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.organization')),
                ('owner_sales_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('pincode', models.CharField(blank=True, max_length=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geofence_radius_meters', models.IntegerField(default=100)),
                ('shift_type', models.CharField(blank=True, choices=[('day', 'Day'), ('night', 'Night'), ('rotational', 'Rotational'), ('custom', 'Custom')], max_length=16)),
                ('contact_person', models.CharField(blank=True, max_length=128)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='sites.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sites', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_profiles', to='core.organization')),
                ('scope_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_profiles', to='core.scopenode')),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_rate', models.DecimalField(decimal_places=2, help_text='Site-level monthly billing rate', max_digits=12)),
                ('approved_budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercials', to='sites.siteprofile')),
            ],
            options={
                'verbose_name': 'Site Commercial',
                'verbose_name_plural': 'Site Commercials',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SiteRoleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_headcount', models.PositiveIntegerField()),
                ('billing_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('wage_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wage_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shift_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('billing_type', models.CharField(choices=[('billable', 'Billable'), ('non_billable', 'Non-Billable')], default='billable', max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_requirements', to='jobs.jobrole')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='sites.siteprofile')),
                ('wage_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_requirements', to='wages.wagecategory')),
            ],
            options={
                'verbose_name': 'Site Role Requirement',
                'verbose_name_plural': 'Site Role Requirements',
                'ordering': ['site', 'job_role', '-effective_from'],
                'indexes': [models.Index(fields=['site', 'job_role', 'is_active'], name='sites_siter_site_id_20d7fc_idx'), models.Index(fields=['billing_type'], name='sites_siter_billing_e33f93_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='siterolerequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('site', 'job_role', 'effective_from'), name='unique_active_site_role_requirement'),
        ),
        migrations.AlterUniqueTogether(
            name='siteprofile',
            unique_together={('org', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('org', 'code')},
        ),
    ]
