# Generated by Django 4.2.29 on 2026-05-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='scope_node',
            field=models.ForeignKey(blank=True, help_text='Client-level scope node used for client admins and client-wide access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profiles', to='core.scopenode'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['org', 'scope_node'], name='sites_clien_org_id_c00a23_idx'),
        ),
    ]
