# Generated by Django 4.2.29 on 2026-05-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0001_initial'),
        ('sites', '0002_client_scope_node_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterolerequirement',
            name='wage_rate',
            field=models.ForeignKey(blank=True, help_text='MinimumWageRate matched by wage lookup at the time of create/update.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_requirements', to='wages.minimumwagerate'),
        ),
        migrations.AddField(
            model_name='siterolerequirement',
            name='wage_rate_daily_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='siterolerequirement',
            name='wage_rate_effective_from_snapshot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterolerequirement',
            name='wage_rate_monthly_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='siterolerequirement',
            name='wage_rate_source_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
