# Generated by Django 4.2.29 on 2026-05-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0002_locationarea_minimumwagerate_org_and_more'),
        ('sites', '0003_siterolerequirement_wage_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='location_area',
            field=models.ForeignKey(blank=True, help_text='Structured location master. Takes precedence over state/city in wage lookup.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='wages.locationarea'),
        ),
    ]
