# Generated by Django 4.2.29 on 2026-05-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_department'),
        ('sites', '0004_site_location_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterolerequirement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_role_requirements', to='core.department'),
        ),
        migrations.AddIndex(
            model_name='siterolerequirement',
            index=models.Index(fields=['site', 'department', 'job_role', 'is_active'], name='sites_siter_site_id_7e01a4_idx'),
        ),
    ]
