# Generated by Django 4.2.29 on 2026-05-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('intake', 'Intake'), ('talent', 'Talent'), ('sites', 'Sites'), ('wages', 'Wages'), ('mrf', 'MRF'), ('workflow', 'Workflow'), ('hiring', 'Hiring'), ('deployment', 'Deployment'), ('client_portal', 'Client Portal'), ('field_sense', 'Field Sense'), ('reports', 'Reports')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('override_parent', models.BooleanField(default=False, help_text='If True, overrides parent scope node activation setting.')),
                ('scope_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_activations', to='core.scopenode')),
            ],
            options={
                'verbose_name': 'Module Activation',
                'verbose_name_plural': 'Module Activations',
                'ordering': ['module'],
                'indexes': [models.Index(fields=['scope_node', 'module'], name='modules_mod_scope_n_0371e9_idx')],
                'unique_together': {('module', 'scope_node')},
            },
        ),
    ]
