# Generated by Django 4.2.29 on 2026-05-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Wage Category',
                'verbose_name_plural': 'Wage Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MinimumWageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=128)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('monthly_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(blank=True, help_text='Optional role-specific wage override. Null means applies to all roles in category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage_rates', to='jobs.jobrole')),
                ('wage_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_rates', to='wages.wagecategory')),
            ],
            options={
                'verbose_name': 'Minimum Wage Rate',
                'verbose_name_plural': 'Minimum Wage Rates',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['state', 'city'], name='wages_minim_state_2ce2d9_idx'), models.Index(fields=['wage_category'], name='wages_minim_wage_ca_66320e_idx'), models.Index(fields=['role'], name='wages_minim_role_id_b12768_idx'), models.Index(fields=['effective_from'], name='wages_minim_effecti_16d464_idx')],
            },
        ),
    ]
