# Generated by Django 4.2.29 on 2026-05-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0001_initial'),
        ('wages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64)),
                ('area_type', models.CharField(choices=[('state', 'State'), ('region', 'Region'), ('city', 'City'), ('zone', 'Zone')], max_length=16)),
                ('state_name', models.CharField(blank=True, help_text='Denormalized ancestor state name for fast filtering.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Area',
                'verbose_name_plural': 'Location Areas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='minimumwagerate',
            name='org',
            field=models.ForeignKey(blank=True, help_text='Null means applies to all orgs (system-level default).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wage_rates', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='minimumwagerate',
            name='city',
            field=models.CharField(blank=True, help_text='Legacy fallback city.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='minimumwagerate',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role-specific override. Null applies to all roles in the category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage_rates', to='jobs.jobrole'),
        ),
        migrations.AlterField(
            model_name='minimumwagerate',
            name='state',
            field=models.CharField(blank=True, help_text='Legacy fallback when location FK is not set.', max_length=128),
        ),
        migrations.AddIndex(
            model_name='minimumwagerate',
            index=models.Index(fields=['org', 'is_active'], name='wages_minim_org_id_9ec8c6_idx'),
        ),
        migrations.AddField(
            model_name='locationarea',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wages.locationarea'),
        ),
        migrations.AddField(
            model_name='minimumwagerate',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Structured location from LocationArea master. Takes precedence over state/city.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage_rates', to='wages.locationarea'),
        ),
        migrations.AddIndex(
            model_name='minimumwagerate',
            index=models.Index(fields=['location'], name='wages_minim_locatio_54a527_idx'),
        ),
        migrations.AddIndex(
            model_name='locationarea',
            index=models.Index(fields=['code'], name='wages_locat_code_706c04_idx'),
        ),
        migrations.AddIndex(
            model_name='locationarea',
            index=models.Index(fields=['area_type'], name='wages_locat_area_ty_8dfe9c_idx'),
        ),
        migrations.AddIndex(
            model_name='locationarea',
            index=models.Index(fields=['parent'], name='wages_locat_parent__7dd338_idx'),
        ),
        migrations.AddIndex(
            model_name='locationarea',
            index=models.Index(fields=['is_active'], name='wages_locat_is_acti_63884f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationarea',
            unique_together={('parent', 'code')},
        ),
    ]
