# Generated by Django 4.2.29 on 2026-05-13 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0004_site_location_area'),
        ('core', '0002_add_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=64)),
                ('budget_nature', models.CharField(choices=[('billable', 'Billable'), ('non_billable', 'Non-Billable')], max_length=16)),
                ('budget_type', models.CharField(choices=[('onboarding', 'Onboarding'), ('manpower', 'Manpower'), ('hiring', 'Hiring'), ('operations', 'Operations'), ('deployment', 'Deployment'), ('general', 'General')], default='general', max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('inactive', 'Inactive')], default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_plans', to='sites.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_plans', to='core.department')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plans', to='core.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_plans', to='sites.siteprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Plan',
                'verbose_name_plural': 'Budget Plans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org', 'budget_nature', 'status'], name='budgets_bud_org_id_c0f381_idx'), models.Index(fields=['org', 'client', 'site'], name='budgets_bud_org_id_9c5249_idx'), models.Index(fields=['org', 'department'], name='budgets_bud_org_id_816bb0_idx'), models.Index(fields=['period_start', 'period_end'], name='budgets_bud_period__55a39c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('org', 'code'), name='unique_active_budget_code_per_org'),
        ),
    ]
