# Generated by Django 4.2.29 on 2026-05-14 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_department'),
        ('mrf', '0003_add_budget_plan_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('committed', 'Committed'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='reserved', max_length=16)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('budget_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='budgets.budgetplan')),
                ('line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_reservations', to='mrf.mrflineitem')),
                ('mrf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_reservations', to='mrf.manpowerrequest')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_reservations', to='core.organization')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_reservations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Reservation',
                'verbose_name_plural': 'Budget Reservations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mrf', 'status'], name='budgets_bud_mrf_id_dfcb5c_idx'), models.Index(fields=['budget_plan', 'status'], name='budgets_bud_budget__f8494a_idx')],
            },
        ),
    ]
