# Generated by Django 4.2.29 on 2026-05-23 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wages', '0002_locationarea_minimumwagerate_org_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('manpower_total', models.PositiveIntegerField(default=0)),
                ('management_fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gst_applicable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sales_review', 'Sales Review'), ('submitted_internal', 'Submitted for Internal Approval'), ('internal_rejected', 'Internal Rejected'), ('internally_approved', 'Internally Approved'), ('sent_to_client', 'Sent to Client'), ('client_negotiation', 'Client Negotiation'), ('client_rejected', 'Client Rejected'), ('client_revision_required', 'Client Revision Required'), ('client_approved', 'Client Approved'), ('locked', 'Locked')], default='draft', max_length=30)),
                ('internal_approval_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='not_started', max_length=20)),
                ('client_approval_status', models.CharField(choices=[('not_sent', 'Not Sent'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('negotiation', 'Negotiation'), ('revision_required', 'Revision Required')], default='not_sent', max_length=20)),
                ('client_remarks', models.TextField(blank=True)),
                ('sales_remarks', models.TextField(blank=True)),
                ('is_final_approved_version', models.BooleanField(default=False)),
                ('sent_to_client_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposal_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposal Version',
                'verbose_name_plural': 'Proposal Versions',
                'ordering': ['lead', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_contact_person', models.CharField(blank=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=32)),
                ('current_stage', models.CharField(choices=[('draft', 'Draft'), ('submitted_to_operations', 'Submitted to Operations'), ('site_survey_in_progress', 'Site Survey In Progress'), ('site_survey_completed', 'Site Survey Completed'), ('budget_generated', 'Budget Generated'), ('sales_review', 'Sales Review'), ('internal_approval', 'Internal Approval'), ('internally_approved', 'Internally Approved'), ('sent_to_client', 'Sent to Client'), ('client_negotiation', 'Client Negotiation'), ('client_revision_required', 'Client Revision Required'), ('client_rejected', 'Client Rejected'), ('client_approved', 'Client Approved'), ('won', 'Won'), ('lost', 'Lost'), ('closed', 'Closed')], default='draft', max_length=40)),
                ('current_status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('blocked', 'Blocked'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('won', 'Won'), ('lost', 'Lost'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('rfp_required', models.BooleanField(default=False)),
                ('rfq_required', models.BooleanField(default=False)),
                ('requirement_details', models.TextField(blank=True)),
                ('initial_business_requirement', models.TextField(blank=True)),
                ('sales_remarks', models.TextField(blank=True)),
                ('converted_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_leads', to=settings.AUTH_USER_MODEL)),
                ('final_approved_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_for_leads', to='sales.proposalversion')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_leads', to='core.organization')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sales_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Lead',
                'verbose_name_plural': 'Sales Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesLeadSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(max_length=255)),
                ('site_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='sales.saleslead')),
                ('location_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_lead_sites', to='wages.locationarea')),
            ],
            options={
                'verbose_name': 'Sales Lead Site',
                'verbose_name_plural': 'Sales Lead Sites',
                'ordering': ['lead', 'site_name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_date', models.DateField(blank=True, null=True)),
                ('business_volume', models.TextField(blank=True)),
                ('service_type', models.CharField(blank=True, max_length=128)),
                ('feasibility_status', models.CharField(choices=[('pending', 'Pending'), ('feasible', 'Feasible'), ('not_feasible', 'Not Feasible'), ('needs_review', 'Needs Review')], default='pending', max_length=20)),
                ('survey_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='sales.saleslead')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='sales.salesleadsite')),
                ('survey_done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Survey',
                'verbose_name_plural': 'Site Surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesRoleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_category', models.CharField(blank=True, max_length=128)),
                ('manpower_count', models.PositiveIntegerField(default=1)),
                ('shift_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('working_days', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_role_requirements', to='jobs.jobrole')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='sales.saleslead')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='sales.salesleadsite')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_requirements', to='sales.sitesurvey')),
                ('wage_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_role_requirements', to='wages.wagecategory')),
            ],
            options={
                'verbose_name': 'Sales Role Requirement',
                'verbose_name_plural': 'Sales Role Requirements',
                'ordering': ['lead', 'site', 'job_role'],
            },
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_versions', to='sales.saleslead'),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='sales.proposalversion'),
        ),
        migrations.CreateModel(
            name='ProposalBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_category', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('manpower_count', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_budget_lines', to='jobs.jobrole')),
                ('proposal_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='sales.proposalversion')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_budget_lines', to='sales.salesleadsite')),
            ],
            options={
                'verbose_name': 'Proposal Budget Line',
                'verbose_name_plural': 'Proposal Budget Lines',
                'ordering': ['proposal_version', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProposalBreakupLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_name', models.CharField(max_length=128)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('employee_deduction', 'Employee Deduction'), ('employer_contribution', 'Employer Contribution'), ('statutory', 'Statutory'), ('reimbursement', 'Reimbursement'), ('equipment', 'Equipment'), ('management_fee', 'Management Fee'), ('tax', 'Tax'), ('total', 'Total')], max_length=30)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_breakup_lines', to='jobs.jobrole')),
                ('proposal_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakup_lines', to='sales.proposalversion')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_breakup_lines', to='sales.salesleadsite')),
            ],
            options={
                'verbose_name': 'Proposal Breakup Line',
                'verbose_name_plural': 'Proposal Breakup Lines',
                'ordering': ['proposal_version', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientProposalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_to_client_at', models.DateTimeField(blank=True, null=True)),
                ('client_response', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('negotiation_required', 'Negotiation Required'), ('revision_required', 'Revision Required')], default='pending', max_length=30)),
                ('client_remarks', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_responses', to='sales.saleslead')),
                ('proposal_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_responses', to='sales.proposalversion')),
                ('sent_to_client_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Proposal Response',
                'verbose_name_plural': 'Client Proposal Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sitesurvey',
            constraint=models.UniqueConstraint(fields=('lead', 'site'), name='uq_site_survey_lead_site'),
        ),
        migrations.AddIndex(
            model_name='saleslead',
            index=models.Index(fields=['org', 'current_stage'], name='sales_sales_org_id_2d7e96_idx'),
        ),
        migrations.AddIndex(
            model_name='saleslead',
            index=models.Index(fields=['org', 'current_status'], name='sales_sales_org_id_db7623_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposalversion',
            constraint=models.UniqueConstraint(fields=('lead', 'version_number'), name='uq_proposal_lead_version'),
        ),
    ]
