# Generated by Django 4.2.29 on 2026-05-23 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproposalresponse',
            name='meeting_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientproposalresponse',
            name='next_action_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproposalresponse',
            name='responded_by_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='clientproposalresponse',
            name='responded_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proposalbreakupline',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalbreakupline',
            name='overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalbreakupline',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_proposal_breakup_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalbreakupline',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalbreakupline',
            name='role_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_breakup_lines', to='sales.salesrolerequirement'),
        ),
        migrations.AddField(
            model_name='proposalbudgetline',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalbudgetline',
            name='overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalbudgetline',
            name='overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_proposal_budget_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalbudgetline',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalbudgetline',
            name='role_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_budget_lines', to='sales.salesrolerequirement'),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='client_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='internally_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='submitted_internal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalversion',
            name='validity_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='estimated_monthly_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='expected_contract_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='expected_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='industry',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='lead_source',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='operations_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sales_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='submitted_to_operations_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleslead',
            name='submitted_to_operations_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_sales_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesrolerequirement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrolerequirement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales_role_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesrolerequirement',
            name='approved_by_operations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesrolerequirement',
            name='created_from_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesurvey',
            name='survey_notes',
            field=models.TextField(blank=True),
        ),
    ]
