# Generated by Django 4.2.29 on 2026-05-25 06:34

import apps.sales.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0007_saleslead_lead_type_and_existing_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('lead_created', 'Lead Created'), ('submitted_to_operations', 'Submitted to Operations'), ('survey_assigned', 'Survey Assigned'), ('survey_started', 'Survey Started'), ('survey_completed', 'Survey Completed'), ('role_requirement_added', 'Role Requirement Added'), ('role_requirement_approved', 'Role Requirement Approved'), ('proposal_generated', 'Proposal Generated'), ('proposal_submitted_internal', 'Proposal Submitted for Internal Approval'), ('proposal_internally_approved', 'Proposal Internally Approved'), ('proposal_internal_rejected', 'Proposal Internal Rejected'), ('proposal_sent_to_client', 'Proposal Sent to Client'), ('client_response_received', 'Client Response Received'), ('proposal_revision_created', 'Proposal Revision Created'), ('lead_won', 'Lead Won'), ('mobilisation_created', 'Mobilisation Created'), ('converted', 'Converted'), ('document_uploaded', 'Document Uploaded'), ('note_added', 'Note Added')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sales.saleslead')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_activities', to='core.organization')),
                ('proposal_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='sales.proposalversion')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='sales.salesleadsite')),
            ],
            options={
                'verbose_name': 'Sales Lead Activity',
                'verbose_name_plural': 'Sales Lead Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org', 'lead', 'activity_type'], name='sales_sales_org_id_4c711e_idx'), models.Index(fields=['org', 'lead', 'created_at'], name='sales_sales_org_id_aed0c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('rfp', 'RFP'), ('rfq', 'RFQ'), ('site_survey_photo', 'Site Survey Photo'), ('site_survey_document', 'Site Survey Document'), ('proposal_pdf', 'Proposal PDF'), ('signed_approval', 'Signed Approval'), ('po', 'Purchase Order'), ('contract', 'Contract'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.sales.models._sales_document_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.saleslead')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_documents', to='core.organization')),
                ('proposal_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sales.proposalversion')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sales.salesleadsite')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sales_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Document',
                'verbose_name_plural': 'Sales Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org', 'lead', 'document_type'], name='sales_sales_org_id_c6a7ce_idx'), models.Index(fields=['org', 'lead', 'is_active'], name='sales_sales_org_id_a418fe_idx')],
            },
        ),
    ]
