# Generated by Django 4.2.30 on 2026-05-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_department'),
        ('sales', '0008_activity_and_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSurveyShiftDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('general_count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('first_shift_count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('second_shift_count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('line_type', models.CharField(choices=[('item', 'Item'), ('subtotal', 'Sub Total'), ('total', 'Total')], default='item', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_deployments', to='sales.sitesurvey')),
            ],
            options={
                'verbose_name': 'Site Survey Shift Deployment Row',
                'verbose_name_plural': 'Site Survey Shift Deployment Rows',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSurveyScopeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('client_scope_site', 'Client Scope / Site Details'), ('premises', 'Premises Details'), ('hk_info', 'HK Information'), ('technical_scope', 'Technical Scope'), ('existing_deployment', 'Existing Deployment Structure')], max_length=32)),
                ('field_key', models.CharField(max_length=64)),
                ('field_label', models.CharField(max_length=200)),
                ('value_text', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_answers', to='sales.sitesurvey')),
            ],
            options={
                'verbose_name': 'Site Survey Scope Answer',
                'verbose_name_plural': 'Site Survey Scope Answers',
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSurveyLocationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_name', models.CharField(max_length=255)),
                ('present_count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proposed_count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('line_type', models.CharField(choices=[('item', 'Item'), ('total', 'Total')], default='item', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_lines', to='sales.sitesurvey')),
            ],
            options={
                'verbose_name': 'Site Survey Location Line',
                'verbose_name_plural': 'Site Survey Location Lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSurveyIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.CharField(max_length=500)),
                ('improvement_details', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_lines', to='sales.sitesurvey')),
            ],
            options={
                'verbose_name': 'Site Survey Issue Line',
                'verbose_name_plural': 'Site Survey Issue Lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSurveyEquipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_category', models.CharField(choices=[('major', 'Major Equipment'), ('minor', 'Minor Equipment')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('unit_count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_type', models.CharField(choices=[('item', 'Item'), ('total', 'Total (Approx.)'), ('amortisation_cost', 'Cost of Amortisation'), ('maintenance_cost', 'Equipment Maintenance & Consumables Cost'), ('amortized_monthly', 'Amortized Monthly Cost'), ('monthly_total', 'Total Equipment Cost per month')], default='item', max_length=24)),
                ('amortisation_months', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_lines', to='sales.sitesurvey')),
            ],
            options={
                'verbose_name': 'Site Survey Equipment Line',
                'verbose_name_plural': 'Site Survey Equipment Lines',
                'ordering': ['equipment_category', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProposalComponentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('component_name', models.CharField(max_length=128)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('employee_deduction', 'Employee Deduction'), ('employer_contribution', 'Employer Contribution'), ('statutory', 'Statutory'), ('reimbursement', 'Reimbursement'), ('equipment', 'Equipment'), ('management_fee', 'Management Fee'), ('tax', 'Tax'), ('total', 'Total')], max_length=32)),
                ('calculation_type', models.CharField(choices=[('percent_of_basic', 'Percent of Basic'), ('percent_of_gross', 'Percent of Gross'), ('percent_of_other', 'Percent of Other Component'), ('fixed', 'Fixed Amount')], max_length=24)),
                ('percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('base_component_code', models.CharField(blank=True, max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_component_rules', to='core.organization')),
            ],
            options={
                'verbose_name': 'Proposal Component Rule',
                'verbose_name_plural': 'Proposal Component Rules',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='sitesurveyshiftdeployment',
            constraint=models.UniqueConstraint(fields=('survey', 'description'), name='uq_survey_shift_deployment_desc'),
        ),
        migrations.AddConstraint(
            model_name='sitesurveyscopeanswer',
            constraint=models.UniqueConstraint(fields=('survey', 'category', 'field_key'), name='uq_survey_scope_answer_key'),
        ),
        migrations.AddConstraint(
            model_name='sitesurveylocationline',
            constraint=models.UniqueConstraint(fields=('survey', 'location_name'), name='uq_survey_location_line_name'),
        ),
        migrations.AddConstraint(
            model_name='sitesurveyissueline',
            constraint=models.UniqueConstraint(fields=('survey', 'issue'), name='uq_survey_issue_line'),
        ),
        migrations.AddConstraint(
            model_name='sitesurveyequipmentline',
            constraint=models.UniqueConstraint(fields=('survey', 'equipment_category', 'description'), name='uq_survey_equipment_line'),
        ),
        migrations.AddIndex(
            model_name='proposalcomponentrule',
            index=models.Index(fields=['org', 'is_active'], name='sales_propo_org_id_9311a6_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalcomponentrule',
            index=models.Index(fields=['org', 'code'], name='sales_propo_org_id_aefebf_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposalcomponentrule',
            constraint=models.UniqueConstraint(condition=models.Q(('org__isnull', False)), fields=('org', 'code'), name='uq_proposal_component_rule_org_code'),
        ),
        migrations.AddConstraint(
            model_name='proposalcomponentrule',
            constraint=models.UniqueConstraint(condition=models.Q(('org__isnull', True)), fields=('code',), name='uq_proposal_component_rule_global_code'),
        ),
    ]
