# Generated by Django 4.2.30 on 2026-05-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_survey_excel_structure_and_component_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesurveyequipmentline',
            name='is_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesurveyequipmentline',
            name='not_applicable_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesurveyissueline',
            name='is_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesurveyissueline',
            name='not_applicable_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesurveylocationline',
            name='is_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesurveylocationline',
            name='not_applicable_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesurveyshiftdeployment',
            name='is_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesurveyshiftdeployment',
            name='not_applicable_reason',
            field=models.TextField(blank=True),
        ),
    ]
