# Generated by Django 4.2.30 on 2026-05-28 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0002_locationarea_minimumwagerate_org_and_more'),
        ('jobs', '0001_initial'),
        ('core', '0002_add_department'),
        ('sales', '0010_sitesurveyequipmentline_is_applicable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyRoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description_text', models.CharField(max_length=200)),
                ('service_category', models.CharField(blank=True, max_length=128)),
                ('shift_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('working_days', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_role_mappings', to='jobs.jobrole')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_role_mappings', to='core.organization')),
                ('wage_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_role_mappings', to='wages.wagecategory')),
            ],
            options={
                'verbose_name': 'Survey Role Mapping',
                'verbose_name_plural': 'Survey Role Mappings',
                'ordering': ['org', 'description_text'],
                'indexes': [models.Index(fields=['org', 'description_text'], name='sales_surve_org_id_da1653_idx'), models.Index(fields=['org', 'is_active'], name='sales_surve_org_id_1a42e0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='surveyrolemapping',
            constraint=models.UniqueConstraint(fields=('org', 'description_text'), name='uq_survey_role_mapping_org_description'),
        ),
    ]
