# Generated by Django 4.2.30 on 2026-08-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_salesrolerequirement_first_shift_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalbudgetline',
            name='source_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='proposalbudgetline',
            name='source_unit_cost_origin',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
