# Generated by Django 4.2.30 on 2026-05-08 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_client_scope_node_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intake', '0001_initial'),
        ('talent', '0001_initial'),
        ('jobs', '0001_initial'),
        ('mrf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, help_text='Optional AI/manual match score out of 100.', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('shortlisted', 'Shortlisted'), ('client_review', 'Client Review'), ('interview_scheduled', 'Interview Scheduled'), ('interview_in_progress', 'Interview In Progress'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('offer_released', 'Offer Released'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('deployed', 'Deployed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('shortlisted_at', models.DateTimeField(blank=True, null=True)),
                ('client_visible', models.BooleanField(default=False)),
                ('client_decision', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16, null=True)),
                ('client_decision_at', models.DateTimeField(blank=True, null=True)),
                ('client_decision_note', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_applications', to='talent.candidate')),
                ('client_decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_decisions', to=settings.AUTH_USER_MODEL)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_applications', to='jobs.jobrole')),
                ('mrf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_applications', to='mrf.manpowerrequest')),
                ('mrf_line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_applications', to='mrf.mrflineitem')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_applications', to='core.organization')),
                ('shortlisted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortlisted_applications', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_applications', to='sites.siteprofile')),
                ('source_intake_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_applications', to='intake.intakesubmission')),
            ],
            options={
                'verbose_name': 'Hiring Application',
                'verbose_name_plural': 'Hiring Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_type', models.CharField(choices=[('hr', 'HR'), ('technical', 'Technical'), ('manager', 'Manager'), ('client', 'Client'), ('final', 'Final')], max_length=16)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=16)),
                ('mode', models.CharField(choices=[('phone', 'Phone'), ('video', 'Video'), ('in_person', 'In Person')], default='in_person', max_length=16)),
                ('location', models.TextField(blank=True)),
                ('meeting_link', models.URLField(blank=True)),
                ('hiring_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='hiring.hiringapplication')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interviews', to=settings.AUTH_USER_MODEL)),
                ('scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('proceed', 'Proceed'), ('hold', 'Hold'), ('reject', 'Reject')], max_length=16)),
                ('given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='hiring.interview')),
            ],
            options={
                'verbose_name': 'Interview Feedback',
                'verbose_name_plural': 'Interview Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_breakup', models.JSONField(blank=True, default=dict)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='draft', max_length=16)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('hiring_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='hiring.hiringapplication')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='hiring_offe_status_7811fe_idx'), models.Index(fields=['joining_date'], name='hiring_offe_joining_c2d6bb_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='interviewfeedback',
            constraint=models.UniqueConstraint(condition=models.Q(('given_by__isnull', False)), fields=('interview', 'given_by'), name='unique_feedback_per_interviewer'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['hiring_application', 'round_number'], name='hiring_inte_hiring__64ff6f_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status', 'scheduled_at'], name='hiring_inte_status_455d84_idx'),
        ),
        migrations.AddIndex(
            model_name='hiringapplication',
            index=models.Index(fields=['org', 'status'], name='hiring_hiri_org_id_eaf71d_idx'),
        ),
        migrations.AddIndex(
            model_name='hiringapplication',
            index=models.Index(fields=['site', 'status'], name='hiring_hiri_site_id_48e3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='hiringapplication',
            index=models.Index(fields=['candidate', 'status'], name='hiring_hiri_candida_0665be_idx'),
        ),
        migrations.AddIndex(
            model_name='hiringapplication',
            index=models.Index(fields=['mrf_line_item', 'status'], name='hiring_hiri_mrf_lin_570d10_idx'),
        ),
        migrations.AddConstraint(
            model_name='hiringapplication',
            constraint=models.UniqueConstraint(fields=('candidate', 'mrf_line_item'), name='unique_candidate_per_mrf_line_item'),
        ),
    ]
