# Generated by Django 4.2.29 on 2026-05-14 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0003_add_budget_plan_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0002_talent_hiring_a'),
        ('core', '0002_add_department'),
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('stage_type', models.CharField(choices=[('sourcing', 'Sourcing'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('onboarding', 'Onboarding')], max_length=20)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='core.organization')),
            ],
            options={
                'verbose_name': 'Pipeline Stage',
                'verbose_name_plural': 'Pipeline Stages',
                'ordering': ['org', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CandidateMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('match_reason', models.TextField(blank=True)),
                ('match_details', models.JSONField(blank=True, default=dict)),
                ('match_source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI'), ('rules', 'Rules-Based')], default='manual', max_length=16)),
                ('is_auto_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='talent.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_match_results', to=settings.AUTH_USER_MODEL)),
                ('mrf_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='mrf.mrflineitem')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='core.organization')),
            ],
            options={
                'verbose_name': 'Candidate Match Result',
                'verbose_name_plural': 'Candidate Match Results',
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(blank=True, max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hiring.pipelinestage')),
                ('hiring_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='hiring.hiringapplication')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_stage_moves', to=settings.AUTH_USER_MODEL)),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hiring.pipelinestage')),
            ],
            options={
                'verbose_name': 'Application Stage History',
                'verbose_name_plural': 'Application Stage Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hiringapplication',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_applications', to='hiring.pipelinestage'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('org', 'code'), name='unique_active_pipeline_stage_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='candidatematchresult',
            index=models.Index(fields=['candidate', 'mrf_line_item'], name='hiring_cand_candida_ba3807_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatematchresult',
            index=models.Index(fields=['org', 'match_source'], name='hiring_cand_org_id_232d2b_idx'),
        ),
    ]
