# Generated by Django 4.2.30 on 2026-06-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_department'),
        ('jobs', '0001_initial'),
        ('hiring', '0004_match_result_availability_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_plans', to='jobs.jobrole')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_plans', to='core.organization')),
            ],
            options={
                'verbose_name': 'Interview Plan',
                'verbose_name_plural': 'Interview Plans',
                'ordering': ['org', 'job_role_id', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=16),
        ),
        migrations.CreateModel(
            name='InterviewPlanRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_type', models.CharField(choices=[('hr', 'HR'), ('technical', 'Technical'), ('manager', 'Manager'), ('client', 'Client'), ('final', 'Final')], max_length=16)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('mode', models.CharField(choices=[('phone', 'Phone'), ('video', 'Video'), ('in_person', 'In Person')], default='video', max_length=16)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='hiring.interviewplan')),
            ],
            options={
                'verbose_name': 'Interview Plan Round',
                'verbose_name_plural': 'Interview Plan Rounds',
                'ordering': ['plan', 'round_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='hiringapplication',
            name='interview_plan',
            field=models.ForeignKey(blank=True, help_text='Selected interview plan for this application, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='hiring.interviewplan'),
        ),
        migrations.AddField(
            model_name='interview',
            name='planned_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='hiring.interviewplanround'),
        ),
        migrations.AddIndex(
            model_name='interviewplanround',
            index=models.Index(fields=['plan', 'is_active'], name='hiring_inte_plan_id_7d5c31_idx'),
        ),
        migrations.AddConstraint(
            model_name='interviewplanround',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('plan', 'round_number'), name='unique_active_interview_plan_round_number'),
        ),
        migrations.AddIndex(
            model_name='interviewplan',
            index=models.Index(fields=['org', 'is_active'], name='hiring_inte_org_id_ffff32_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewplan',
            index=models.Index(fields=['job_role', 'is_active'], name='hiring_inte_job_rol_f8d0b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='interviewplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('org', 'code'), name='unique_active_interview_plan_code_per_org'),
        ),
    ]
