# Generated by Django 4.2.29 on 2026-05-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScopeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('node_type', models.CharField(choices=[('company', 'Company'), ('client', 'Client'), ('region', 'Region'), ('city', 'City'), ('site', 'Site'), ('department', 'Department'), ('cost_center', 'Cost Center')], max_length=32)),
                ('path', models.CharField(blank=True, db_index=True, max_length=1024)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_nodes', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.scopenode')),
            ],
            options={
                'verbose_name': 'Scope Node',
                'verbose_name_plural': 'Scope Nodes',
                'ordering': ['depth', 'name'],
                'indexes': [models.Index(fields=['path'], name='core_scopen_path_42a7a2_idx'), models.Index(fields=['org', 'node_type'], name='core_scopen_org_id_2c9c27_idx'), models.Index(fields=['org', 'is_active'], name='core_scopen_org_id_204f90_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scopenode',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('org', 'code'), name='unique_root_scope_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='scopenode',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('org', 'parent', 'code'), name='unique_child_scope_code_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='scopenode',
            constraint=models.UniqueConstraint(condition=models.Q(('path', ''), _negated=True), fields=('org', 'path'), name='unique_scope_path_per_org'),
        ),
    ]
