# Generated by Django 4.2.29 on 2026-05-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0001_initial'),
        ('sites', '0001_initial'),
        ('jobs', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=128)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('select', 'Select'), ('multiselect', 'Multi-Select'), ('date', 'Date'), ('file', 'File'), ('number', 'Number'), ('textarea', 'Text Area'), ('checkbox', 'Checkbox')], default='text', max_length=16)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'ordering': ['campaign', 'order'],
            },
        ),
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Intake Submission',
                'verbose_name_plural': 'Intake Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_campaigns', to='core.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_campaigns', to='sites.siteprofile')),
            ],
            options={
                'verbose_name': 'QR Campaign',
                'verbose_name_plural': 'QR Campaigns',
                'ordering': ['-created_at'],
                'unique_together': {('org', 'code')},
            },
        ),
        migrations.CreateModel(
            name='IntakeSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='intake.formfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='intake.intakesubmission')),
            ],
            options={
                'verbose_name': 'Intake Submission Answer',
                'verbose_name_plural': 'Intake Submission Answers',
            },
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='intake.qrcampaign'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_submissions', to='talent.candidate'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_submissions', to='sites.siteprofile'),
        ),
        migrations.CreateModel(
            name='IntakeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(upload_to='intake-documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='intake.intakesubmission')),
            ],
            options={
                'verbose_name': 'Intake Document',
                'verbose_name_plural': 'Intake Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='intake.qrcampaign'),
        ),
        migrations.CreateModel(
            name='CampaignJobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_job_roles', to='intake.qrcampaign')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_job_roles', to='jobs.jobrole')),
            ],
            options={
                'verbose_name': 'Campaign Job Role',
                'verbose_name_plural': 'Campaign Job Roles',
                'unique_together': {('campaign', 'job_role')},
            },
        ),
    ]
