# Generated by Django 4.2.29 on 2026-05-08 14:20

import apps.intake.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_phase3e_intake_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='intakesubmission',
            new_name='intake_inta_mobile__2007f7_idx',
            old_name='intake_intak_mobile__idx',
        ),
        migrations.RenameIndex(
            model_name='intakesubmission',
            new_name='intake_inta_status_f9440a_idx',
            old_name='intake_intak_status_idx',
        ),
        migrations.RenameIndex(
            model_name='intakesubmission',
            new_name='intake_inta_campaig_c866a7_idx',
            old_name='intake_intak_camp_mob_idx',
        ),
        migrations.RenameIndex(
            model_name='intakesubmission',
            new_name='intake_inta_campaig_e6a956_idx',
            old_name='intake_intak_camp_mob_role_idx',
        ),
        migrations.RenameIndex(
            model_name='intakesubmission',
            new_name='intake_inta_candida_c195d6_idx',
            old_name='intake_intak_cand_camp_idx',
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='qrcampaign',
            name='enabled_languages',
            field=models.JSONField(default=apps.intake.models._default_enabled_languages),
        ),
    ]
