# Generated by Django 4.2.29 on 2026-05-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('core', '0002_add_department'),
        ('intake', '0003_rename_intake_intak_mobile__idx_intake_inta_mobile__2007f7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Form Section',
                'verbose_name_plural': 'Form Sections',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='intakedocument',
            name='field_source',
            field=models.CharField(choices=[('campaign', 'Campaign'), ('template', 'Template')], default='campaign', max_length=10),
        ),
        migrations.AddField(
            model_name='intakesubmissionanswer',
            name='field_source',
            field=models.CharField(choices=[('campaign', 'Campaign'), ('template', 'Template')], default='campaign', max_length=10),
        ),
        migrations.AlterField(
            model_name='intakesubmissionanswer',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='intake.formfield'),
        ),
        migrations.CreateModel(
            name='FormTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_key', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('boolean', 'Boolean'), ('file', 'File')], default='text', max_length=20)),
                ('help_text', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('options', models.JSONField(default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_fields', to='jobs.jobrole')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_fields', to='intake.formsection')),
            ],
            options={
                'verbose_name': 'Form Template Field',
                'verbose_name_plural': 'Form Template Fields',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='core.organization')),
            ],
            options={
                'verbose_name': 'Form Template',
                'verbose_name_plural': 'Form Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='formsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='intake.formtemplate'),
        ),
        migrations.AddField(
            model_name='intakedocument',
            name='template_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='intake.formtemplatefield'),
        ),
        migrations.AddField(
            model_name='intakesubmissionanswer',
            name='template_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='intake.formtemplatefield'),
        ),
        migrations.AddField(
            model_name='qrcampaign',
            name='form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='intake.formtemplate'),
        ),
    ]
