# Generated by Django 4.2.29 on 2026-05-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_form_builder_backend_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsection',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='formtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('org', 'code'), name='uq_form_template_org_code'),
        ),
    ]
