# Generated by Django 4.2.29 on 2026-05-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64)),
                ('node_type_scope', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Access Role',
                'verbose_name_plural': 'Access Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('reassign', 'Reassign'), ('start_workflow', 'Start Workflow'), ('manage_module', 'Manage Module'), ('manage', 'Manage'), ('export', 'Export'), ('view_resume', 'View Resume'), ('shortlist', 'Shortlist')], max_length=32)),
                ('resource', models.CharField(choices=[('organization', 'Organization'), ('user', 'User'), ('role', 'Role'), ('module', 'Module'), ('client', 'Client'), ('site', 'Site'), ('site_role_requirement', 'Site Role Requirement'), ('job_role', 'Job Role'), ('campaign', 'Campaign'), ('submission', 'Submission'), ('candidate', 'Candidate'), ('resume', 'Resume'), ('mrf', 'MRF'), ('workflow', 'Workflow'), ('wage', 'Wage'), ('budget', 'Budget'), ('interview', 'Interview'), ('offer', 'Offer'), ('deployment', 'Deployment'), ('report', 'Report'), ('field_tracking', 'Field Tracking')], max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['resource', 'action'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
            },
        ),
        migrations.CreateModel(
            name='UserScopeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary'), ('additional', 'Additional'), ('delegated', 'Delegated')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scope_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scope_assignments', to='core.scopenode')),
            ],
            options={
                'verbose_name': 'User Scope Assignment',
                'verbose_name_plural': 'User Scope Assignments',
            },
        ),
    ]
