# Generated by Django 4.2.30 on 2026-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(choices=[('organization', 'Organization'), ('user', 'User'), ('role', 'Role'), ('module', 'Module'), ('client', 'Client'), ('site', 'Site'), ('site_role_requirement', 'Site Role Requirement'), ('job_role', 'Job Role'), ('campaign', 'Campaign'), ('submission', 'Submission'), ('candidate', 'Candidate'), ('resume', 'Resume'), ('mrf', 'MRF'), ('workflow', 'Workflow'), ('wage', 'Wage'), ('budget', 'Budget'), ('interview', 'Interview'), ('offer', 'Offer'), ('hiring_application', 'Hiring Application'), ('employee', 'Employee'), ('site_deployment', 'Site Deployment'), ('deployment', 'Deployment'), ('report', 'Report'), ('field_tracking', 'Field Tracking')], max_length=64),
        ),
    ]
