# Generated by Django 4.2.29 on 2026-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('client', 'Client'), ('field', 'Field')], default='internal', max_length=16),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['org', 'user_type', 'is_active'], name='accounts_us_org_id_d4ffee_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['org', 'employee_code'], name='accounts_us_org_id_a66151_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_normalized', ''), _negated=True), fields=('org', 'phone_normalized'), name='unique_user_phone_per_org'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code', ''), _negated=True), fields=('org', 'employee_code'), name='unique_user_employee_code_per_org'),
        ),
    ]
