# Generated by Django 4.2.29 on 2026-05-11 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mrf', '0001_initial'),
        ('access', '0003_alter_permission_resource'),
        ('sites', '0004_site_location_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL)),
                ('mrf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='mrf.manpowerrequest')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='core.organization')),
            ],
            options={
                'verbose_name': 'Workflow Instance',
                'verbose_name_plural': 'Workflow Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('trigger_type', models.CharField(choices=[('mrf', 'MRF')], default='mrf', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(blank=True, help_text='Null = system-wide template usable by all orgs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='core.organization')),
            ],
            options={
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
                'ordering': ['org', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_type', models.CharField(choices=[('mrf', 'MRF')], default='mrf', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_template_mappings', to='sites.client')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_template_mappings', to='core.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_template_mappings', to='sites.siteprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='workflow.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Workflow Template Mapping',
                'verbose_name_plural': 'Workflow Template Mappings',
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('assignment_mode', models.CharField(choices=[('named_user', 'Named User'), ('queue', 'Queue'), ('claim', 'Claim')], default='named_user', max_length=16)),
                ('actor_type', models.CharField(choices=[('internal', 'Internal'), ('client', 'Client')], default='internal', max_length=16)),
                ('on_approve_next', models.CharField(blank=True, help_text='Step code to activate on approve. Empty = next sequential. "END" = complete workflow.', max_length=64)),
                ('on_reject_target', models.CharField(blank=True, help_text='Step code to reactivate on reject. Empty = reject workflow.', max_length=64)),
                ('on_request_changes_target', models.CharField(blank=True, help_text='Step code to reactivate on request_changes. Empty = reject workflow.', max_length=64)),
                ('requires_comment_on_reject', models.BooleanField(default=True)),
                ('requires_comment_on_request_changes', models.BooleanField(default=True)),
                ('sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Workflow Step Template',
                'verbose_name_plural': 'Workflow Step Templates',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('step_code', models.CharField(max_length=64)),
                ('step_name', models.CharField(max_length=128)),
                ('assignment_mode', models.CharField(choices=[('named_user', 'Named User'), ('queue', 'Queue'), ('claim', 'Claim')], max_length=16)),
                ('actor_type', models.CharField(choices=[('internal', 'Internal'), ('client', 'Client')], max_length=16)),
                ('on_approve_next', models.CharField(blank=True, max_length=64)),
                ('on_reject_target', models.CharField(blank=True, max_length=64)),
                ('on_request_changes_target', models.CharField(blank=True, max_length=64)),
                ('requires_comment_on_reject', models.BooleanField(default=True)),
                ('requires_comment_on_request_changes', models.BooleanField(default=True)),
                ('sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('request_changes', 'Request Changes'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.CharField(blank=True, choices=[('approve', 'Approve'), ('reject', 'Reject'), ('request_changes', 'Request Changes')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_step_actions', to=settings.AUTH_USER_MODEL)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_step_assignments', to=settings.AUTH_USER_MODEL)),
                ('step_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowsteptemplate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflowinstance')),
            ],
            options={
                'verbose_name': 'Workflow Step Instance',
                'verbose_name_plural': 'Workflow Step Instances',
                'ordering': ['workflow', 'step_order'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Start'), ('approve', 'Approve'), ('reject', 'Reject'), ('request_changes', 'Request Changes'), ('reassign', 'Reassign')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('reassign_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_from_workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('reassign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_to_workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('step_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='workflow.workflowstepinstance')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='workflow.workflowinstance')),
            ],
            options={
                'verbose_name': 'Workflow Action',
                'verbose_name_plural': 'Workflow Actions',
                'ordering': ['workflow', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepAssignmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_type', models.CharField(choices=[('mrf', 'MRF')], default='mrf', max_length=32)),
                ('step_code', models.CharField(max_length=64)),
                ('assignment_mode', models.CharField(choices=[('named_user', 'Named User'), ('queue', 'Queue'), ('claim', 'Claim')], default='named_user', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_assignment_configs', to='sites.client')),
                ('eligible_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_assignment_configs', to='access.accessrole')),
                ('eligible_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_assignment_configs', to='core.scopenode')),
                ('named_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_assignment_configs', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_assignment_configs', to='core.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_assignment_configs', to='sites.siteprofile')),
            ],
            options={
                'verbose_name': 'Step Assignment Config',
                'verbose_name_plural': 'Step Assignment Configs',
            },
        ),
        migrations.AddConstraint(
            model_name='workflowtemplatemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('org', 'trigger_type', 'site'), name='unique_wtm_site'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplatemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False), ('site__isnull', True)), fields=('org', 'trigger_type', 'client'), name='unique_wtm_client'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplatemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True), ('site__isnull', True)), fields=('org', 'trigger_type'), name='unique_wtm_org_default'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('org__isnull', False)), fields=('org', 'code'), name='unique_wt_org_code'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('org__isnull', True)), fields=('code',), name='unique_wt_global_code'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowsteptemplate',
            unique_together={('template', 'order'), ('template', 'code')},
        ),
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('mrf',), name='unique_active_workflow_per_mrf'),
        ),
        migrations.AddConstraint(
            model_name='stepassignmentconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('org', 'trigger_type', 'step_code', 'site'), name='unique_sac_site'),
        ),
        migrations.AddConstraint(
            model_name='stepassignmentconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False), ('site__isnull', True)), fields=('org', 'trigger_type', 'step_code', 'client'), name='unique_sac_client'),
        ),
        migrations.AddConstraint(
            model_name='stepassignmentconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True), ('site__isnull', True)), fields=('org', 'trigger_type', 'step_code'), name='unique_sac_org_default'),
        ),
    ]
