# Generated by Django 4.2.29 on 2026-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_redesign_workflow_engine'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stepassignmentconfig',
            name='unique_sac_site',
        ),
        migrations.RemoveConstraint(
            model_name='stepassignmentconfig',
            name='unique_sac_client',
        ),
        migrations.RemoveConstraint(
            model_name='stepassignmentconfig',
            name='unique_sac_org_default',
        ),
        migrations.RemoveConstraint(
            model_name='workflowtemplatemapping',
            name='unique_wtm_site',
        ),
        migrations.RemoveConstraint(
            model_name='workflowtemplatemapping',
            name='unique_wtm_client',
        ),
        migrations.RemoveConstraint(
            model_name='workflowtemplatemapping',
            name='unique_wtm_org_default',
        ),
        migrations.AlterField(
            model_name='workflowstepinstance',
            name='actor_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('client', 'Client'), ('field', 'Field')], max_length=16),
        ),
        migrations.AlterField(
            model_name='workflowsteptemplate',
            name='actor_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('client', 'Client'), ('field', 'Field')], default='internal', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='stepassignmentconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('site__isnull', False)), fields=('org', 'trigger_type', 'step_code', 'site'), name='unique_sac_site'),
        ),
        migrations.AddConstraint(
            model_name='stepassignmentconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False), ('is_active', True), ('site__isnull', True)), fields=('org', 'trigger_type', 'step_code', 'client'), name='unique_sac_client'),
        ),
        migrations.AddConstraint(
            model_name='stepassignmentconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True), ('is_active', True), ('site__isnull', True)), fields=('org', 'trigger_type', 'step_code'), name='unique_sac_org_default'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplatemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('site__isnull', False)), fields=('org', 'trigger_type', 'site'), name='unique_wtm_site'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplatemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False), ('is_active', True), ('site__isnull', True)), fields=('org', 'trigger_type', 'client'), name='unique_wtm_client'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplatemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True), ('is_active', True), ('site__isnull', True)), fields=('org', 'trigger_type'), name='unique_wtm_org_default'),
        ),
    ]
