# Generated by Django 4.2.29 on 2026-05-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_department'),
        ('workflow', '0002_fix_constraints_and_actor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepassignmentconfig',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Expected department for the assigned user. Validated at workflow start.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_assignment_configs', to='core.department'),
        ),
        migrations.AddField(
            model_name='workflowstepinstance',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_step_assignments', to='core.department'),
        ),
        migrations.AddField(
            model_name='workflowstepinstance',
            name='assigned_department_code_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workflowstepinstance',
            name='assigned_department_name_snapshot',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
