# Generated by Django 4.2.29 on 2026-05-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0002_manpowerrequest_requesting_department_and_more'),
        ('mobilisation', '0001_initial'),
        ('workflow', '0003_department_aware_workflow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowinstance',
            name='unique_active_workflow_per_mrf',
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='client_onboarding_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='mobilisation.mobilisationsetuprequest'),
        ),
        migrations.AlterField(
            model_name='stepassignmentconfig',
            name='trigger_type',
            field=models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Client Onboarding')], default='mrf', max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='mrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='mrf.manpowerrequest'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='trigger_type',
            field=models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Client Onboarding')], default='mrf', max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowtemplatemapping',
            name='trigger_type',
            field=models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Client Onboarding')], default='mrf', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('mrf__isnull', False), ('status', 'active')), fields=('mrf',), name='unique_active_workflow_per_mrf'),
        ),
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('client_onboarding_request__isnull', False), ('status', 'active')), fields=('client_onboarding_request',), name='unique_active_workflow_per_onboarding'),
        ),
    ]
