# Generated by Django 4.2.29 on 2026-05-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_remove_workflowinstance_unique_active_workflow_per_mrf_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('client_onboarding_request__isnull', True), ('mrf__isnull', False)), models.Q(('client_onboarding_request__isnull', False), ('mrf__isnull', True)), _connector='OR'), name='workflow_instance_exactly_one_target'),
        ),
    ]
