# Generated by Django 4.2.29 on 2026-05-14 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0004_site_location_area'),
        ('workflow', '0005_workflowinstance_workflow_instance_exactly_one_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('trigger_type', models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Client Onboarding')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_routes', to='sites.client')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_routes', to='core.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_routes', to='sites.siteprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_routes', to='workflow.workflowtemplate')),
            ],
            options={
                'verbose_name': 'Approval Route',
                'verbose_name_plural': 'Approval Routes',
                'ordering': ['org', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='approval_route_code_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='approval_route_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ApprovalRouteStepAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_code', models.CharField(max_length=64)),
                ('assignment_mode', models.CharField(choices=[('named_user', 'Named User'), ('queue', 'Queue'), ('claim', 'Claim')], default='named_user', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_route_step_assignments', to='core.department')),
                ('named_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_route_step_assignments', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_assignments', to='workflow.approvalroute')),
            ],
            options={
                'verbose_name': 'Approval Route Step Assignment',
                'verbose_name_plural': 'Approval Route Step Assignments',
                'ordering': ['route', 'step_code'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='approval_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances', to='workflow.approvalroute'),
        ),
        migrations.AddConstraint(
            model_name='approvalroutestepassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('route', 'step_code'), name='unique_arsa_route_step'),
        ),
        migrations.AddConstraint(
            model_name='approvalroute',
            constraint=models.UniqueConstraint(fields=('org', 'code'), name='unique_ar_org_code'),
        ),
        migrations.AddConstraint(
            model_name='approvalroute',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True), ('site__isnull', False)), fields=('org', 'trigger_type', 'site'), name='unique_ar_default_site'),
        ),
        migrations.AddConstraint(
            model_name='approvalroute',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False), ('is_active', True), ('is_default', True), ('site__isnull', True)), fields=('org', 'trigger_type', 'client'), name='unique_ar_default_client'),
        ),
        migrations.AddConstraint(
            model_name='approvalroute',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True), ('is_active', True), ('is_default', True), ('site__isnull', True)), fields=('org', 'trigger_type'), name='unique_ar_default_org'),
        ),
    ]
