# Generated by Django 4.2.30 on 2026-05-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_workflow_sales_proposal_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalroute',
            name='trigger_type',
            field=models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Mobilisation'), ('sales_proposal', 'Sales Proposal')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stepassignmentconfig',
            name='trigger_type',
            field=models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Mobilisation'), ('sales_proposal', 'Sales Proposal')], default='mrf', max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='trigger_type',
            field=models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Mobilisation'), ('sales_proposal', 'Sales Proposal')], default='mrf', max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowtemplatemapping',
            name='trigger_type',
            field=models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Mobilisation'), ('sales_proposal', 'Sales Proposal')], default='mrf', max_length=32),
        ),
    ]
