# Generated by Django 4.2.30 on 2026-07-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_alter_approvalroute_trigger_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTATSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_type', models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Mobilisation'), ('sales_proposal', 'Sales Proposal')], max_length=32, unique=True)),
                ('default_sla_hours', models.PositiveIntegerField(default=72)),
            ],
            options={
                'verbose_name': 'Workflow TAT Setting',
                'verbose_name_plural': 'Workflow TAT Settings',
                'ordering': ['trigger_type'],
            },
        ),
    ]
