# Generated by Django 4.2.30 on 2026-07-07 09:21

from django.db import migrations


def create_fast_track_flow(apps, schema_editor):
    Organization = apps.get_model('core', 'Organization')
    WorkflowTemplate = apps.get_model('workflow', 'WorkflowTemplate')
    WorkflowStepTemplate = apps.get_model('workflow', 'WorkflowStepTemplate')
    ApprovalRoute = apps.get_model('workflow', 'ApprovalRoute')
    StepAssignmentConfig = apps.get_model('workflow', 'StepAssignmentConfig')
    AccessRole = apps.get_model('access', 'AccessRole')
    StepAssignmentConfig = apps.get_model('workflow', 'StepAssignmentConfig')
    AccessRole = apps.get_model('access', 'AccessRole')

    # Iterate over all organizations
    for org in Organization.objects.all():
        # Create Fast Track Template
        template, created = WorkflowTemplate.objects.get_or_create(
            org=org,
            code='mrf_fast_track',
            defaults={
                'name': 'Fast Track MRF Workflow',
                'trigger_type': 'mrf',
                'version': 1,
                'description': 'Bypasses Finance and Admin reviews. For billable MRFs without deviations.',
                'is_active': True,
            }
        )

        if created:
            # Create Steps: Client -> HR -> Client
            WorkflowStepTemplate.objects.create(
                template=template,
                order=10,
                code='client_initial_review',
                name='Client Initial Review',
                assignment_mode='named_user',
                actor_type='client',
                on_approve_next='hr_review',
                on_reject_target='',
                on_request_changes_target='',
            )
            WorkflowStepTemplate.objects.create(
                template=template,
                order=20,
                code='hr_review',
                name='HR Review',
                assignment_mode='named_user',
                actor_type='internal',
                on_approve_next='client_final_review',
                on_reject_target='client_initial_review',
                on_request_changes_target='client_initial_review',
            )
            WorkflowStepTemplate.objects.create(
                template=template,
                order=30,
                code='client_final_review',
                name='Client Final Review',
                assignment_mode='named_user',
                actor_type='client',
                on_approve_next='END',
                on_reject_target='hr_review',
                on_request_changes_target='hr_review',
            )

        # Create Approval Route
        ApprovalRoute.objects.get_or_create(
            org=org,
            code='fast_track_default',
            defaults={
                'name': 'Fast Track Approval Route',
                'trigger_type': 'mrf',
                'template': template,
                'description': 'Default fast track route for billable MRFs',
                'is_default': False,
                'is_active': True,
            }
        )

def remove_fast_track_flow(apps, schema_editor):
    WorkflowTemplate = apps.get_model('workflow', 'WorkflowTemplate')
    ApprovalRoute = apps.get_model('workflow', 'ApprovalRoute')
    ApprovalRoute.objects.filter(code='fast_track_default').delete()
    WorkflowTemplate.objects.filter(code='mrf_fast_track').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_workflowtatsetting'),
    ]

    operations = [
        migrations.RunPython(create_fast_track_flow, remove_fast_track_flow),
    ]

