# Generated by Django 4.2.30 on 2026-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_add_fast_track_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalroute',
            name='trigger_type',
            field=models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Mobilisation'), ('sales_proposal', 'Sales Proposal'), ('inventory_request', 'Inventory Request')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stepassignmentconfig',
            name='trigger_type',
            field=models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Mobilisation'), ('sales_proposal', 'Sales Proposal'), ('inventory_request', 'Inventory Request')], default='mrf', max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowtatsetting',
            name='trigger_type',
            field=models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Mobilisation'), ('sales_proposal', 'Sales Proposal'), ('inventory_request', 'Inventory Request')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='trigger_type',
            field=models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Mobilisation'), ('sales_proposal', 'Sales Proposal'), ('inventory_request', 'Inventory Request')], default='mrf', max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowtemplatemapping',
            name='trigger_type',
            field=models.CharField(choices=[('mrf', 'MRF'), ('client_onboarding', 'Mobilisation'), ('sales_proposal', 'Sales Proposal'), ('inventory_request', 'Inventory Request')], default='mrf', max_length=32),
        ),
    ]
