# Generated by Django 4.2.29 on 2026-05-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('skill_category', models.CharField(choices=[('unskilled', 'Unskilled'), ('semi_skilled', 'Semi-Skilled'), ('skilled', 'Skilled'), ('highly_skilled', 'Highly Skilled'), ('supervisor', 'Supervisor')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='core.organization')),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'ordering': ['name'],
                'unique_together': {('org', 'code')},
            },
        ),
    ]
