# Generated by Django 4.2.30 on 2026-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='True if this is an internal role'),
        ),
    ]
